version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ai-talks"
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env