version: "3.8"

services:
  app:
    image: "w0rng/ai-talks:latest"
    container_name: "ai-talks"
    restart: unless-stopped
    volumes:
      - ./promts.yml:/app/promts.yml
    ports:
      - "80:8501"
    env_file:
      - .env
